### ISSUE TITLE
Add restart functionality from topic page

### ISSUE THREAD

**Issue by JessicaLoers** [neuefische/quiz-app#12]

**Comment by JessicaLoers** [comment]
## Value Proposition

**As a** user
**I want** to repeat a quiz
**to be able to** test and train my knowledge.

## Description
TopicPage after all questions of the session HTML Forms are answered - rather correct or incorrect
![Image](https://user-images.githubusercontent.com/54777853/214598764-ab820275-e25c-4c4b-80f0-25acf80d7e01.png)



## Acceptance Criteria

### TopicPage: `[topicSlug]/index.js`:

**Case:  all questions of the session are answered**
**component `LinkCard`**
- [ ] the restart button is displayed
- [ ] when clicking the `restart button` the current progress of the is reset fromm 100% to 0%
- [ ] when clicking of the LinkCard the quiz start from the beginning 

**component `ProgessBar`**
- [ ] when clicking the `restart button` the current topic progress is reset according to the number of questions.

**Case:  some or zero questions of the sessions are answered**
- [ ] the `restart button` is not visible


## Tasks
 - [ ] implement logic for update the `userAnswers` in localStorage
 - [ ] component `LinkCard`
    - [ ] implement the conditionally `restart button` 
    - [ ] update component
    - [ ] update story and tests
 - [ ] component `ProgressBar`
    - [ ] update story and test if the progress is reset according to the restarted quiz/session
